version: '3.8'

services:
  graph:
    image: benmandrew/rose:graph
    build:
      context: .
      dockerfile: docker/Dockerfile.graph
    volumes:
      - shared:/app/shared
    environment:
      BFS_MAX_DEPTH: "100"
      BFS_TIMEOUT_S: "0.5"
    restart: "no"
    init: true
    healthcheck:
      test: ["CMD", "test", "-f", "/app/shared/graph.json"]
      interval: 1s
      timeout: 1s
      retries: 12

  web:
    image: benmandrew/rose:web
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "8080:8080"
    volumes:
      - shared:/usr/src/app/shared
    depends_on:
      graph:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:8080/graph.json"]
      interval: 1s
      timeout: 1s
      retries: 12

volumes:
  shared:
